/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.RGBWColor;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
@SuppressWarnings("unused")
public class LightsSys extends SubsystemBase {
    private final CANBus kCANBus = new CANBus("CANivore");
    private final CANdle m_candle = new CANdle(17, kCANBus);

    private final SolidColor[] Red = new SolidColor[] {
      new SolidColor(8, 233).withColor(new RGBWColor(255, 0, 0, 0))
    };
    private final SolidColor[] Blue = new SolidColor[] {
      new SolidColor(8, 233).withColor(new RGBWColor(0, 0, 255, 0))
    };
    private final SolidColor[] White = new SolidColor[] {
      new SolidColor(8, 233).withColor(new RGBWColor(255, 255,255, 255))
    };


    public LightsSys() {
        // Run the LED updater continuously so it can switch colors at runtime.
        setDefaultCommand(updateLEDs().ignoringDisable(true));
    }

    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
             if (isHubActive()) {
              for (var solidColor : White) {
                    m_candle.setControl(solidColor);
                }
            }  
            else {
                if (DriverStation.getAlliance().isPresent() && DriverStation.getAlliance().get() == Alliance.Red) {
                for (var solidColor : Red) {
                    m_candle.setControl(solidColor);
                }} else {
                  for (var solidColor : Blue) {
                    m_candle.setControl(solidColor);
                }
                }
            }
        });
    }

  /**
   * Determines if the hub is active based on the current match state and game data.
   * The hub is active during autonomous, and during teleop it shifts between active and inactive based on the match time and which alliance won autonomous.
   * @return true if the hub is active, false otherwise.
   */
	public boolean isHubActive() {
  Optional<Alliance> alliance = DriverStation.getAlliance();
  // If we have no alliance, we cannot be enabled, therefore no hub.
  if (alliance.isEmpty()) {
    return false;
  }
  // Hub is always enabled in autonomous.
  if (DriverStation.isAutonomousEnabled()) {
    return true;
  }
  // At this point, if we're not teleop enabled, there is no hub.
  if (!DriverStation.isEnabled()) {
    return false;
  }
  

  // We're teleop enabled, compute.
  double matchTime = DriverStation.getMatchTime();
  String gameData = DriverStation.getGameSpecificMessage();
  // If we have no game data, we cannot compute, assume hub is active, as its likely early in teleop.
  if (gameData.isEmpty()) {
    return true;
  }
  boolean redInactiveFirst = false;
  switch (gameData.charAt(0)) {
    case 'R' -> redInactiveFirst = true;
    case 'B' -> redInactiveFirst = false;
    default -> {
      // If we have invalid game data, assume hub is active.
      return true;
    }
  }

  // Shift was is active for blue if red won auto, or red if blue won auto.
  boolean shift1Active = switch (alliance.get()) {
    case Red -> !redInactiveFirst;
    case Blue -> redInactiveFirst;
  };

  if (matchTime > 130) {
    // Transition shift, hub is active.
    return true;
  } else if (matchTime > 105) {
    // Shift 1
    return shift1Active;
  } else if (matchTime > 80) {
    // Shift 2
    return !shift1Active;
  } else if (matchTime > 55) {
    // Shift 3
    return shift1Active;
  } else if (matchTime > 30) {
    // Shift 4
    return !shift1Active;
  } else {
    // End game, hub always active.
    return true;
  }
}
}
